# Generated by Django 4.2.23 on 2025-08-08 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('no_carrinho', 'No carrinho'), ('solicitado', 'Solicitado'), ('em_producao', 'Em produção'), ('entregue', 'Entregue')], default='no_carrinho', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoNoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.pedido')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.produto')),
            ],
        ),
    ]
